-- MySQL Script generated by MySQL Workbench
-- Wed Nov 11 15:58:52 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema school
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema school
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `school` DEFAULT CHARACTER SET utf8 ;
USE `school` ;

-- -----------------------------------------------------
-- Table `school`.`Adresse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school`.`Adresse` (
  `IdAdresse` INT NOT NULL AUTO_INCREMENT,
  `rue` VARCHAR(45) NULL,
  `numero` VARCHAR(45) NULL,
  `ville` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IdAdresse`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school`.`Etudiant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school`.`Etudiant` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `diplome` VARCHAR(45) NULL,
  `Adresse_IdAdresse` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Etudiant_Adresse1_idx` (`Adresse_IdAdresse` ASC) VISIBLE,
  CONSTRAINT `fk_Etudiant_Adresse1`
    FOREIGN KEY (`Adresse_IdAdresse`)
    REFERENCES `school`.`Adresse` (`IdAdresse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school`.`Professeur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school`.`Professeur` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `competence` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school`.`Salle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school`.`Salle` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nom_UNIQUE` (`nom` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school`.`Cours`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school`.`Cours` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `heureDebut` TIME NULL,
  `heureFIN` TIME NULL,
  `Professeur_id` INT NOT NULL,
  `Salle_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Cours_Professeur1_idx` (`Professeur_id` ASC) VISIBLE,
  INDEX `fk_Cours_Salle1_idx` (`Salle_id` ASC) VISIBLE,
  CONSTRAINT `fk_Cours_Professeur1`
    FOREIGN KEY (`Professeur_id`)
    REFERENCES `school`.`Professeur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cours_Salle1`
    FOREIGN KEY (`Salle_id`)
    REFERENCES `school`.`Salle` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school`.`Participant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school`.`Participant` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `place` VARCHAR(45) NULL,
  `Cours_id` INT NOT NULL,
  `Etudiant_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Participant_Cours1_idx` (`Cours_id` ASC) VISIBLE,
  INDEX `fk_Participant_Etudiant1_idx` (`Etudiant_id` ASC) VISIBLE,
  CONSTRAINT `fk_Participant_Cours1`
    FOREIGN KEY (`Cours_id`)
    REFERENCES `school`.`Cours` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Participant_Etudiant1`
    FOREIGN KEY (`Etudiant_id`)
    REFERENCES `school`.`Etudiant` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
